import { InputConfig } from "@/hooks/use-input-config"
import type { BaseInputProps } from "@/components/blinks-ui-0.13.1/internal/inputs/types"

export const GENERATOR: Partial<Record<InputConfig, BaseInputProps>> = {
  [InputConfig.Text]: {
    type: "text",
    placeholder: "Text ",
    name: "name",
    disabled: true,
    required: false,
    min: undefined,
    max: undefined,
    pattern: undefined,
    description: undefined,
    button: undefined,
    options: undefined,
  },
  [InputConfig.Number]: {
    type: "number",
    placeholder: "Number ",
    name: "name",
    disabled: true,
    required: false,
    min: undefined,
    max: undefined,
    pattern: undefined,
    description: undefined,
    button: undefined,
    options: undefined,
  },
  [InputConfig.Date]: {
    type: "date",
    placeholder: "Date ",
    name: "date",
    disabled: false,
    required: false,
    min: undefined,
    max: undefined,
    pattern: undefined,
    description: undefined,
    button: undefined,
    options: undefined,
  },
  [InputConfig.Radio]: {
    type: "radio",
    placeholder: "Radio",
    name: "radio",
    disabled: false,
    required: false,
    min: undefined,
    max: undefined,
    pattern: undefined,
    description: undefined,
    button: undefined,
    options: [
      {
        label: "Option 1",
        value: "option1",
      },
      {
        label: "Option 2",
        value: "option2",
      },
    ],
  },
  [InputConfig.Select]: {
    type: "select",
    placeholder: "Select",
    name: "select",
    disabled: false,
    required: false,
    min: undefined,
    max: undefined,
    pattern: undefined,
    description: undefined,
    button: undefined,
    options: [
      {
        label: "Option 1",
        value: "option1",
      },
      {
        label: "Option 2",
        value: "option2",
      },
    ],
  },
  [InputConfig.Checkbox]: {
    type: "checkbox",
    placeholder: "Checkbox",
    name: "checkbox",
    disabled: false,
    required: false,
    min: undefined,
    max: undefined,
    pattern: undefined,
    description: undefined,
    button: undefined,
    options: [
      {
        label: "Option 1",
        value: "option1",
      },
      {
        label: "Option 2",
        value: "option2",
      },
    ],
  },
}
